services:
  http-request-tool:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PATH=/data/history.db
    restart: unless-stopped
