apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-request-tool
  labels:
    app: http-request-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-request-tool
  template:
    metadata:
      labels:
        app: http-request-tool
    spec:
      containers:
      - name: http-request-tool
        image: http-request-tool:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
