# Voorbeeld: Create een image pull secret voor GitHub Container Registry
# 
# Stap 1: Maak een GitHub Personal Access Token met 'read:packages' scope
# Ga naar: https://github.com/settings/tokens
#
# Stap 2: Create het secret in je K8s cluster:
#
# kubectl create secret docker-registry ghcr-secret \
#   --docker-server=ghcr.io \
#   --docker-username=<GITHUB_USERNAME> \
#   --docker-password=<GITHUB_TOKEN> \
#   --docker-email=<YOUR_EMAIL>
#
# Of gebruik dit manifest (vervang de base64 encoded credentials):

apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG>

# Om de base64 string te genereren:
# echo -n '{"auths":{"ghcr.io":{"username":"<USERNAME>","password":"<TOKEN>","email":"<EMAIL>","auth":"<BASE64_OF_USERNAME:TOKEN>"}}}' | base64
